# Generated by Django 5.0.7 on 2024-07-30 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
